kotlin.code.style=official
erika_version=1.1.14
# Dependencies
# ESL
reactor_core_version=3.6.3
coroutines_version=1.8.1
guava_version=33.0.0
gson_version=2.8.9
reflections_version=0.10.2
dateparser_version=1.0.11
esl_version=1.0.2
log4j_version=2.19.0
slf4j_version=2.0.4
ktor_version=2.3.11
mongo_version=5.0.0
# ACF
brigadier_version=1.0.18
acf_version=2.0.2
# Buster
buster_version=1.1.0
semver_version=5.4.1
# Kord
kord_version=0.14.0
emoji_version=5.1.1
